[package]
name = "armv7"
version = "0.1.0"
authors = ["Moritz Doll"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
register = "^0.5.0"
